// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"basic-go/week4/wire/repository"
	"basic-go/week4/wire/repository/dao"
)

// Injectors from wire.go:

func initUserRepository() *repository.UserRepository {
	db := initDB()
	userDAO := dao.NewUserDAO(db)
	userRepository := repository.NewUserRepository(userDAO)
	return userRepository
}
